### ISSUE TITLE
Developers screen not working

### ISSUE THREAD

**Issue by Nackoo2000** [breez/l-breez#40]
When I enter in the developers screen the UI is not right and I can't enter any command or choose from a menu.
![image](https://github.com/breez/l-breez/assets/127208515/6dfd29d1-b681-4079-8937-6849511d3ef1)

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 It's disabled by choice. We don't have any commands that's beneficial to run from this screen on Liquid SDK at the moment.
