### ISSUE TITLE
Scaning a bolt 11 does not work from the send menu

### ISSUE THREAD

**Issue by Nackoo2000** [breez/l-breez#54]
1. Create a bolt 11 on another device
2. Click on Send > Send via Invoice
3. Click on the scanning button
4. Scan the QR
5. Click approve
6. It says "Unsupported input"
![image](https://github.com/user-attachments/assets/1c064ef0-7246-41f5-95aa-9b6c87c0f98d)

Scanning the QR from the scan button (the one between send and receive) works properly.

Android 8.0 on a Sony Xperia device

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 please share logs.

**Comment by Nackoo2000** [comment]
This is working now so case closed.
