### ISSUE TITLE
Bad UX when trying to send under the limit

### ISSUE THREAD

**Issue by Nackoo2000** [breez/l-breez#55]
1. Receive > Receive via Invoice
2. Enter an amount under 1000 sats
3. Click the button "Create"
4. Nothing happens

There should be a text in yellow under the amount field saying that the minimum is 1000 sats to create an invoice.

![image](https://github.com/user-attachments/assets/40837092-1789-4b1e-b5ea-5267a034ef5d)

**Comment by erdemyerebasmaz** [comment]
Re: https://github.com/breez/l-breez/issues/3
